# =============================================================================
# FlakeCache nix-csi CSI Driver Registration
# =============================================================================
#
# PURPOSE:
# Registers the nix-csi driver with Kubernetes, enabling pods to request
# Nix store volumes through the standard Kubernetes storage API.
#
# HOW CSI WORKS:
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │                         CSI Architecture                                 │
# │                                                                          │
# │  Pod Spec                      Kubernetes                 nix-csi       │
# │  ────────                      ──────────                 ───────       │
# │                                                                          │
# │  volumes:                                                                │
# │  - name: nix        ────►  CSIDriver: nix.csi.store  ────►  DaemonSet   │
# │    csi:                    (this file)                      nix-node    │
# │      driver: nix.csi.store                                     │        │
# │      volumeAttributes:                                         │        │
# │        substituters: ...                                       ▼        │
# │                                                          Mount /nix     │
# │                                                          into pod       │
# └─────────────────────────────────────────────────────────────────────────┘
#
# CSI DRIVER SPEC:
#
# attachRequired: false
#   - Volumes don't need controller attachment (no remote storage)
#   - nix-csi provides local node storage from host's /nix
#
# podInfoOnMount: true
#   - CSI receives pod name, namespace, UID when mounting
#   - Enables per-pod audit logging and resource tracking
#
# volumeLifecycleModes: [Ephemeral]
#   - Supports inline ephemeral volumes (defined in pod spec)
#   - No PVC required - simpler for CI/CD workloads
#   - Volume lifecycle tied to pod lifecycle
#
# STORAGE CLASS:
# The StorageClass allows using nix-csi with PersistentVolumeClaims:
#   - provisioner: nix.csi.store (matches CSIDriver name)
#   - volumeBindingMode: Immediate (bind as soon as PVC created)
#
# USAGE EXAMPLES:
#
# 1. Inline ephemeral volume (recommended for runners):
#    ```yaml
#    volumes:
#    - name: nix
#      csi:
#        driver: nix.csi.store
#        volumeAttributes:
#          substituters: "https://cache.nixos.org"
#    ```
#
# 2. PersistentVolumeClaim (for stateful workloads):
#    ```yaml
#    volumes:
#    - name: nix
#      persistentVolumeClaim:
#        claimName: my-nix-store
#    ---
#    apiVersion: v1
#    kind: PersistentVolumeClaim
#    spec:
#      storageClassName: nix-csi
#      accessModes: [ReadWriteOnce]
#      resources:
#        requests:
#          storage: 10Gi
#    ```
#
# CURRENT DEPLOYMENT:
# For GitHub Actions runners, we use host path mounts directly instead of
# CSI volumes. This is simpler and avoids CSI driver complexity:
#   - /var/flakecache/nix -> /nix (read-only)
#   - /var/run/nix-daemon-socket -> /nix/var/nix/daemon-socket
#
# The CSI driver is provided for future use cases requiring dynamic
# provisioning or per-pod isolation.
#
# =============================================================================

# -----------------------------------------------------------------------------
# CSIDriver
# Tells Kubernetes about the nix-csi driver capabilities
# -----------------------------------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nix.csi.store
  labels:
    app.kubernetes.io/name: nix-csi
    app.kubernetes.io/part-of: flakecache
spec:
  # No controller attachment needed - volumes are node-local
  attachRequired: false

  # Pass pod info to CSI for logging/auditing
  podInfoOnMount: true

  # Support ephemeral inline volumes (defined in pod spec, not PVC)
  volumeLifecycleModes:
    - Ephemeral

  # Don't require volume ownership changes (Nix store is shared)
  fsGroupPolicy: None

  # Storage capacity tracking not needed for shared store
  storageCapacity: false

---
# -----------------------------------------------------------------------------
# StorageClass
# Enables PersistentVolumeClaim usage with nix-csi
# -----------------------------------------------------------------------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nix-csi
  labels:
    app.kubernetes.io/name: nix-csi
    app.kubernetes.io/part-of: flakecache
  annotations:
    # Not the default storage class - users must explicitly request
    storageclass.kubernetes.io/is-default-class: "false"
# CSI driver that handles provisioning
provisioner: nix.csi.store
# Bind immediately (no topology constraints)
volumeBindingMode: Immediate
# Volumes can be shared read-only
allowVolumeExpansion: false
# Default mount options
mountOptions: []
# Parameters passed to CSI driver
parameters:
  # Default substituters (can be overridden per-PVC)
  substituters: "https://cache.nixos.org"
