# =============================================================================
# FlakeCache Nix Daemon DaemonSet
# =============================================================================
#
# PURPOSE:
# Provides a shared Nix daemon on each Kubernetes node that:
# 1. Manages a shared /nix/store across all pods on the node
# 2. Enforces signature verification (require-sigs=true)
# 3. Pulls from configured binary caches (nixos.org, Cachix, Determinate, Attic)
#
# THIS IS THE RECOMMENDED DEPLOYMENT for GitHub Actions runners.
# Simpler than the full CSI driver approach, with the same benefits.
#
# ARCHITECTURE:
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │                      Kubernetes Node                                     │
# │                                                                          │
# │  ┌───────────────────────────────────────────────────────────────────┐  │
# │  │               nix-daemon Pod (DaemonSet)                           │  │
# │  │                                                                    │  │
# │  │  ┌─────────────────────┐     ┌─────────────────────────────────┐  │  │
# │  │  │   init-nix-store    │     │        nix-daemon               │  │  │
# │  │  │                     │     │                                 │  │  │
# │  │  │ - Check if /nix     │     │ - Listens on Unix socket        │  │  │
# │  │  │   exists on host    │     │ - Manages /nix/store            │  │  │
# │  │  │ - Copy base store   │     │ - Verifies signatures           │  │  │
# │  │  │   if empty          │     │ - Pulls from binary caches      │  │  │
# │  │  │ - Mark initialized  │     │                                 │  │  │
# │  │  └─────────────────────┘     └─────────────────────────────────┘  │  │
# │  │           │                              │                         │  │
# │  │           ▼                              ▼                         │  │
# │  │  /var/flakecache/nix              /var/run/nix-daemon-socket      │  │
# │  │  (host path)                      (host path)                      │  │
# │  └───────────────────────────────────────────────────────────────────┘  │
# │                    │                        │                           │
# │                    │    mounted by          │                           │
# │                    ▼    runner pods         ▼                           │
# │  ┌───────────────────────────────────────────────────────────────────┐  │
# │  │            GitHub Actions Runner Pod                               │  │
# │  │                                                                    │  │
# │  │   /nix (read-only)  ────────────► /var/flakecache/nix             │  │
# │  │   /nix/var/nix/daemon-socket ───► /var/run/nix-daemon-socket      │  │
# │  │                                                                    │  │
# │  │   NIX_REMOTE=daemon                                               │  │
# │  │   FLAKECACHE_RUNNER=true                                          │  │
# │  │                                                                    │  │
# │  └───────────────────────────────────────────────────────────────────┘  │
# └─────────────────────────────────────────────────────────────────────────┘
#
# BINARY CACHE INTEGRATION:
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │                        Binary Cache Flow                                 │
# │                                                                          │
# │  Runner: nix build nixpkgs#hello                                        │
# │              │                                                           │
# │              │ NIX_REMOTE=daemon                                        │
# │              ▼                                                           │
# │  nix-daemon receives request                                            │
# │              │                                                           │
# │              │ Check substituters in order:                             │
# │              ▼                                                           │
# │  1. cache.nixos.org ──────────── Official packages                      │
# │  2. nix-community.cachix.org ─── Community (devenv, home-manager)       │
# │  3. cache.determinate.systems ── Determinate (nix-installer)            │
# │  4. attic.actions-runner... ──── Internal Attic cache                   │
# │              │                                                           │
# │              │ Verify signature with trusted-public-keys                │
# │              ▼                                                           │
# │  Copy to /nix/store (shared across all pods)                            │
# └─────────────────────────────────────────────────────────────────────────┘
#
# SECURITY MODEL:
#
# 1. require-sigs = true
#    - ALL store paths must be cryptographically signed
#    - Prevents supply chain attacks via unsigned packages
#    - Ed25519 signatures verified against trusted-public-keys
#
# 2. Read-only /nix mount for runners
#    - Runners cannot directly modify /nix/store
#    - All writes go through daemon socket
#    - Daemon controls what gets installed
#
# 3. Privileged daemon only
#    - Only the daemon pod needs privileges
#    - Runner pods are unprivileged
#    - Minimal attack surface
#
# TRUSTED PUBLIC KEYS:
#
# ┌────────────────────────────────────────────────────────────────────────┐
# │ Cache                  │ Key Name               │ Purpose              │
# ├────────────────────────────────────────────────────────────────────────┤
# │ cache.nixos.org        │ cache.nixos.org-1      │ Official NixOS       │
# │ nix-community.cachix   │ nix-community...org-1  │ Community packages   │
# │ cache.determinate      │ cache.determinate...-1 │ Determinate Systems  │
# │ Attic (internal)       │ singularity            │ Your private cache   │
# └────────────────────────────────────────────────────────────────────────┘
#
# HOST PATHS:
#
# /var/flakecache/nix
#   - Persistent Nix store on the host
#   - Survives pod restarts
#   - Shared across all pods on the node
#   - Initialize once, reuse forever
#
# /var/run/nix-daemon-socket
#   - Unix domain socket directory
#   - Contains: socket file for nix-daemon communication
#   - Mounted into runner pods at /nix/var/nix/daemon-socket
#
# DEPLOYMENT:
#
#   # Deploy namespace and RBAC first (optional, for CSI)
#   kubectl apply -f namespace.yaml
#
#   # Deploy this DaemonSet
#   kubectl apply -f nix-daemon-daemonset.yaml
#
#   # Verify daemon is running on all nodes
#   kubectl get pods -n nix-csi -l app.kubernetes.io/name=nix-daemon
#   kubectl logs -n nix-csi -l app.kubernetes.io/name=nix-daemon
#
# TROUBLESHOOTING:
#
#   # Check daemon logs
#   kubectl logs -n nix-csi -l app.kubernetes.io/name=nix-daemon -f
#
#   # Verify socket exists on host
#   kubectl exec -n nix-csi -l app.kubernetes.io/name=nix-daemon -- \
#     ls -la /nix/var/nix/daemon-socket/
#
#   # Test nix command through daemon
#   kubectl exec -n nix-csi -l app.kubernetes.io/name=nix-daemon -- \
#     nix --version
#
# =============================================================================
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nix-daemon
  namespace: nix-csi
  labels:
    app.kubernetes.io/name: nix-daemon
    app.kubernetes.io/part-of: flakecache
    app.kubernetes.io/component: daemon
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      # Update one node at a time to maintain Nix availability
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nix-daemon
      app.kubernetes.io/part-of: flakecache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nix-daemon
        app.kubernetes.io/part-of: flakecache
        app.kubernetes.io/component: daemon
    spec:
      # Don't need host PID namespace (more secure)
      hostPID: false

      # -----------------------------------------------------------------------
      # Init Container: Initialize Nix store on host (runs once per node)
      # -----------------------------------------------------------------------
      initContainers:
        - name: init-nix-store
          image: nixos/nix:latest
          command:
            - /bin/sh
            - -c
            - |
              # Initialize /nix on the host if it's empty
              # This only runs once per node - subsequent pods skip this
              if [ ! -f /nix-volume/nix/store/.initialized ]; then
                echo "Initializing Nix store on host..."
                mkdir -p /nix-volume/nix

                # Copy the base Nix installation from the container
                # This includes nix binaries and essential store paths
                cp -a /nix/* /nix-volume/nix/ 2>/dev/null || true

                # Mark as initialized so we don't repeat this
                touch /nix-volume/nix/store/.initialized
                echo "Nix store initialized successfully"
              else
                echo "Nix store already initialized, skipping"
              fi
          volumeMounts:
            - name: nix-store
              mountPath: /nix-volume

      containers:
        # ---------------------------------------------------------------------
        # Main Container: Nix Daemon
        # Manages /nix/store and exposes socket for client communication
        # ---------------------------------------------------------------------
        - name: nix-daemon
          image: nixos/nix:latest
          securityContext:
            # Required for store operations and socket creation
            privileged: true
          command:
            - /bin/sh
            - -c
            - |
              # Configure Nix with strict signature requirements
              mkdir -p /etc/nix
              cat > /etc/nix/nix.conf << 'EOF'
              # Enable modern Nix commands (nix build, nix flake, etc.)
              experimental-features = nix-command flakes

              # Binary caches - order matters, first is checked first
              # 1. Official NixOS cache
              # 2. Cachix nix-community (devenv, home-manager, etc.)
              # 3. Determinate Systems (nix-installer, flakehub)
              # 4. Internal Attic cache (if configured)
              substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.determinate.systems http://attic.actions-runner-system.svc.cluster.local:8080/singularity

              # Public keys for signature verification
              # SECURITY: Only packages signed by these keys are accepted
              trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.determinate.systems-1:DaGv3H0FotMWgU9WTPW+LSVnmW4r40OWsE62aO8x2bI= singularity:nsWPgp0mIC/OZdqnm0UXSOblL37jAHny6zYhqyu6ckk=

              # CRITICAL: Require cryptographic signatures on all store paths
              # This is the main security control - never set to false!
              require-sigs = true

              # Performance settings
              max-jobs = auto
              keep-outputs = true
              builders-use-substitutes = true
              EOF

              # Create socket directory with proper permissions
              # This directory is mounted from host and shared with runner pods
              mkdir -p /nix/var/nix/daemon-socket
              chmod 755 /nix/var/nix/daemon-socket

              echo "Starting nix-daemon..."
              echo "Substituters: cache.nixos.org, nix-community.cachix.org, cache.determinate.systems, attic"
              echo "Signature verification: ENABLED (require-sigs=true)"

              # Start the daemon - this blocks and handles client requests
              exec nix-daemon
          env:
            # Don't use daemon mode inside the daemon itself
            - name: NIX_REMOTE
              value: ""
          volumeMounts:
            # Nix store on host (persistent)
            - name: nix-store
              mountPath: /nix
              subPath: nix
            # Daemon socket directory (shared with runner pods)
            - name: nix-socket
              mountPath: /nix/var/nix/daemon-socket

      # -----------------------------------------------------------------------
      # Volumes
      # -----------------------------------------------------------------------
      volumes:
        # Persistent Nix store on the host
        # DirectoryOrCreate: creates /var/flakecache if it doesn't exist
        - name: nix-store
          hostPath:
            path: /var/flakecache
            type: DirectoryOrCreate

        # Daemon socket shared with runner pods
        # DirectoryOrCreate: creates socket directory if needed
        - name: nix-socket
          hostPath:
            path: /var/run/nix-daemon-socket
            type: DirectoryOrCreate

---
# =============================================================================
# Headless Service for nix-daemon
# =============================================================================
#
# PURPOSE:
# Provides DNS resolution for nix-daemon pods. Not strictly required for
# host path based communication, but useful for monitoring and debugging.
#
# DNS: nix-daemon.nix-csi.svc.cluster.local
#
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: nix-daemon
  namespace: nix-csi
  labels:
    app.kubernetes.io/name: nix-daemon
    app.kubernetes.io/part-of: flakecache
spec:
  # Headless service (no cluster IP)
  clusterIP: None
  selector:
    app.kubernetes.io/name: nix-daemon
    app.kubernetes.io/part-of: flakecache
